### ISSUE TITLE
DocumentsContractApi21: java.lang.SecurityException: Permission Denial: writing

### ISSUE THREAD

**Issue by etihwjd** [tachiyomiorg/tachiyomi-preview#17]
Since updating to r6132 (maybe just correlation), I can't read or update any of my titles. I had a pending system update (android 14 QPR 2 -> QPR 2.1), so I updated with no relief. I downgraded to Tachiyomi Preview r6116 and tried the stable version, again with no relief. So I've looked at logs and found the abovementioned error.

When trying to view titles, there's an error showing panels and the app won't show webview versions of the titles. 

I am a Google Play Services beta user and notice that an update to it was released on 27 October (23.43.13 (190408-577232161)) and I wonder whether this could have anything to do with the errors.

```
--------- beginning of main
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: Failed to createFile
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: java.lang.SecurityException: Permission Denial: writing com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/tree/primary%3ATachiyomi%2Fdownload/document/primary%3ATachiyomi%2Fdownload from pid=15578, uid=10569 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:3041)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:3024)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:764)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2466)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1380)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at com.hippo.unifile.Utils.createFile(SourceFile:5)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(SourceFile:30)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardPreview(SourceFile:17)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader.access$downloadChapter(SourceFile:167)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.Downloader$launchDownloadJob$1.invokeSuspend(SourceFile:44)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:112)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
10-28 11:15:40.987 15578 15821 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
10-28 11:15:40.987 15578 15821 E DownloadProvider: Invalid download directory
10-28 11:15:40.987 15578 15821 E DownloadProvider: java.lang.NullPointerException: Attempt to invoke virtual method 'com.hippo.unifile.UniFile com.hippo.unifile.UniFile.createDirectory(java.lang.String)' on a null object reference
10-28 11:15:40.987 15578 15821 E DownloadProvider: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardPreview(SourceFile:25)
10-28 11:15:40.987 15578 15821 E DownloadProvider: 	at eu.kanade.tachiyomi.data.download.Downloader.access$downloadChapter(SourceFile:167)
10-28 11:15:40.987 15578 15821 E DownloadProvider: 	at eu.kanade.tachiyomi.data.download.Downloader$launchDownloadJob$1.invokeSuspend(SourceFile:44)
10-28 11:15:40.987 15578 15821 E DownloadProvider: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
10-28 11:15:40.987 15578 15821 E DownloadProvider: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:112)
10-28 11:15:40.987 15578 15821 E DownloadProvider: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
10-28 11:15:40.987 15578 15821 E DownloadProvider: 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
10-28 11:15:40.987 15578 15821 E DownloadProvider: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
10-28 11:15:40.987 15578 15821 E DownloadProvider: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
10-28 11:15:40.987 15578 15821 E StandaloneCoroutine: java.lang.Exception: Invalid location: com.hippo.unifile.TreeDocumentFile@120f92e
10-28 11:15:40.987 15578 15821 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.getMangaDir$app_standardPreview(SourceFile:94)
10-28 11:15:40.987 15578 15821 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.data.download.Downloader.access$do wnloadChapter(SourceFile:167)
10-28 11:15:40.987 15578 15821 E StandaloneCoroutine: 	at eu.kanade.tachiyomi.data.download.Downloader$launchDownloadJob$1.invokeSuspend(SourceFile:44)
10-28 11:15:40.987 15578 15821 E StandaloneCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
10-28 11:15:40.987 15578 15821 E StandaloneCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:112)
10-28 11:15:40.987 15578 15821 E StandaloneCoroutine: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
10-28 11:15:40.987 15578 15821 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
10-28 11:15:40.987 15578 15821 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
10-28 11:15:40.987 15578 15821 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
App version: 0.14.6-6132 (standard, 8057f067b, 107, 2023-10-25T13:24Z)
Android version: 14 (SDK 34)
Android build ID: U1B2.230922.010
Device brand: google
Device manufacturer: Google
Device name: husky
Device model: Pixel 8 Pro
Device product name: husky_beta
WebView: Android System WebView 119.0.6045.53
```

**Comment by etihwjd** [comment]
An update: Could this be to do with the toonily extension? I got further with webview when investigating the error and got this page:

![Screenshot_20231028-133701](https://github.com/tachiyomiorg/tachiyomi-preview/assets/98606636/9422b829-82cf-4f14-943a-e9e866ede01b)

I'm able to view this particular title using a different extension (toonily.me), but when trying to view another title using Omega Scans extension I get a HTTP 400 error so I'm still perplexed.

**Comment by arkon** [comment]
Sounds like you're lacking storage permissions for the app.

For general support, please use Discord: https://discord.gg/tachiyomi

For app bug reports, please create them here: https://github.com/tachiyomiorg/tachiyomi/issues

**Comment by etihwjd** [comment]
Forgive me, but after using the app for ages across multiple device, why would the storage permissions suddenly present an issue? I can understand if it's a extension issue, but without changing anything aside from the preview version I suddenly experienced these issues. I'm not a developer, but it doesn't make sense to me that it would be a device permission issue.

**Comment by arkon** [comment]
> why would the storage permissions suddenly present an issue?

I'm merely interpreting the log messages, I don't know why it would be an issue on your particular device. You could potentially try setting it a different folder.

> I can understand if it's a extension issue, but without changing anything aside from the preview version I suddenly experienced these issues.

Your getting blocked from Toonily seems tangential unless all of your library entries are from it, then it'd make sense that your attempts to update the entries are failing. Either way, you could ask on Discord or maybe create an issue in the correct repo with the proper template that asks for the type of information that'd help people debug it (i.e. actual reproduction steps).
